name: ameliaculwell
favicon: null
layout_spectrum: 0.931584392208606
typography_spectrum: 0.857897523092106
title: Amelia Culwell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5732049215584993
  lightness: 0.25721984379924834
  saturation: 0.2935126321390271
  rhythmicContrast: 0.24853432248346508
purpose: []
